language: java

sudo: required

services:
  - docker

jdk:
  - openjdk11

git:
  depth: 3

before_install:
  - chmod +x mvnw

after_success:
  - docker build -t wernerw/boot-vue-docker .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push wernerw/boot-vue-docker;
    fi
