language: java

sudo: required

services:
  - docker

jdk:
  - openjdk11

git:
  depth: 3

before_install:
  - chmod +x mvnw

after_success:
  - docker build -t wernerw/boot-vue-docker .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
